# github action to deploy interior-coffee api to azure

name: Deploy Interior Coffee API

on:
  workflow_dispatch:

job:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore ./InteriorCoffeeAPIs/InteriorCoffeeAPIs.csproj

    - name: Build
      run: dotnet build ./InteriorCoffeeAPIs/InteriorCoffeeAPIs.csproj --configuration Release --no-restore
